#!/bin/bash

for filepath in ./files/*; do
    [ -f "$filepath" ] || continue

    filename=$(basename "$filepath")
    first_char="${filename:0:1}"
    lower_char="${first_char,,}"

    if [[ "$lower_char" == [a-z] && -d "./$lower_char" ]]; then
        mv "$filepath" "./$lower_char/"
    fi
done
